Use foodhunter;

-- Q1 - How much revenue was generated by FoodHunter in the second half of June 2022? 
select round(sum(final_price) , 2) as TotalRevenue from orders
where order_date >= '2022-06-15' and order_date <= '2022-06-30';

-- Q2.How many restaurants serve “Italian” cuisine on the FoodHunter app? 
select count(distinct(restaurant_id)) as Restaurantcount from restaurants
where cuisine like '%Italian%';

-- Q3.How many orders were placed on 22nd August 2022 with a final price greater than $40?
select count(order_id) as TotalOrder from orders
where final_price > 40 and order_date = '2022-08-22';

-- Q4.How many orders were placed on Saturdays and Sundays, from the 4th of September to the 10th of September? 
select count(order_id) as TotalOrder, sum(final_price) as TotalRevenue,
case
when dayofweek(order_date) = 1 then 'weekend'
when dayofweek(order_date) = 7 then 'weekend'
else 'weekday'
end as wday
from orders
where order_date >= '2022-09-04' and order_date <= '2022-09-10' 
group by wday; 

-- Q5.How many orders were delivered by Driver ID 10 in July 2022 where the total price was greater than $50?
select count(order_id) as TotalOrders
from orders
where order_date >= '2022-07-01' and order_date <= '2022-07-31' and
driver_id = 10 and total_price > 50;

-- Q6. What is the total number of restaurants under each cuisine?
select * from restaurants;
select  cuisine, count(distinct(restaurant_id)) as Restaurantcount from restaurants
group by cuisine;

-- Q7. Write a query to find the number of orders placed on each Monday in the month of September. 
select order_date, count(order_id) as TotalOrder
from orders
where order_date >= '2022-09-01' and order_date <= '2022-09-30' 
and dayofweek(order_date) = 2
group by order_date;


-- Q8.What is the correct query to find the revenue generated by FoodHunter in the first half of September 2022? 
SELECT SUM(final_price) AS total_revenue
FROM orders
WHERE DATE(order_date) BETWEEN '2022-09-01' AND '2022-09-15';
-------------
-- 9.How many orders were placed on 1st July 2022 with a final price of less than $35?
select count(order_id) as TotalOrders
from orders
where order_date = '2022-07-01'and
final_price < 35;

-- Additionals (Total Discount, Total Revenue Query)
select MONTH(order_date) as month,
round(sum(discount),0) as TotalDiscount, 
round(sum(final_price),0) as TotalRevenue
from orders
group by month
order by month;

-- Discount Ratio Query
select MONTH(order_date) as month,
sum(discount) as TotalDiscount, 
sum(final_price) as TotalRevenue,
round((sum(discount) /sum(final_price)), 3) as Discount_Ratio
from orders
group by month
order by month;

-- Week of day Toatl Revenue and Order Count
select dayofweek(order_date) as Wday, 
sum(final_price) as TotalRevenue,
count(order_id) as OrderCount
from orders
group by Wday
order by Wday;

-- weekend and weekday total revenue
select sum(final_price) as TotalRevenue,
count(order_id) as order_count,
case
when dayofweek(order_date) = 1 then 'weekend'
when dayofweek(order_date) = 7 then 'weekend'
else 'weekday'
end as wday
from orders
group by wday;






